import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./_components/Footer";
import { Toaster } from "react-hot-toast";
import { Provider } from "react-redux";
import { store } from "./store/store";  // ✅ Correct import
import ReduxProvider from "./ReduxProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>  
          <Toaster
            toastOptions={{
              style: {
                fontSize: "18px",         // ✅ Larger text
                padding: "20px",          // ✅ More padding
                minWidth: "400px",        // ✅ Wider toast
                minHeight: "100px",       // ✅ Taller toast
                borderRadius: "12px",     // ✅ Rounded corners
                boxShadow: "0 8px 20px rgba(0, 0, 0, 0.2)", // ✅ Enhanced shadow
              },
              success: {
                icon: (
                  <span
                    style={{
                      fontSize: "32px",           // ✅ Large tick icon
                      color: "green",             // ✅ Green color
                      fontWeight: "bold",
                    }}
                  >
                    ✔️
                  </span>
                ),
              }
            }}
            position="top-right"
            reverseOrder={true}
          />
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
